# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jogo_joken_po.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(450, 530)
        Form.setMinimumSize(QtCore.QSize(450, 530))
        Form.setMaximumSize(QtCore.QSize(450, 530))
        Form.setStyleSheet("background-color:rgb(134, 186, 255);")
        self.titulo = QtWidgets.QLabel(Form)
        self.titulo.setGeometry(QtCore.QRect(140, 30, 201, 61))
        self.titulo.setStyleSheet("font: 75 19pt \"MS Shell Dlg 2\";\n"
        "text-decoration: underline;\n"
        "")
        self.titulo.setObjectName("titulo")
        self.btn_pedra = QtWidgets.QPushButton(Form)
        self.btn_pedra.setGeometry(QtCore.QRect(50, 170, 101, 71))
        self.btn_pedra.setStyleSheet("background-color:rgb(127, 127, 127);")
        self.btn_pedra.setObjectName("btn_pedra")
        self.btn_papel = QtWidgets.QPushButton(Form)
        self.btn_papel.setGeometry(QtCore.QRect(170, 170, 101, 71))
        self.btn_papel.setStyleSheet("background-color:rgb(214, 214, 214);")
        self.btn_papel.setObjectName("btn_papel")
        self.btn_tesoura = QtWidgets.QPushButton(Form)
        self.btn_tesoura.setGeometry(QtCore.QRect(300, 170, 101, 71))
        self.btn_tesoura.setStyleSheet("background-color:rgb(200, 87, 67);")
        self.btn_tesoura.setObjectName("btn_tesoura")
        self.resposta = QtWidgets.QLabel(Form)
        self.resposta.setGeometry(QtCore.QRect(60, 280, 331, 111))
        self.resposta.setStyleSheet("background-color:rgb(255, 255, 255);")
        self.resposta.setText("")
        self.resposta.setObjectName("resposta")
        self.btn_reset = QtWidgets.QPushButton(Form)
        self.btn_reset.setGeometry(QtCore.QRect(160, 420, 111, 61))
        self.btn_reset.setStyleSheet("background-color:rgb(143, 150, 158);")
        self.btn_reset.setObjectName("btn_reset")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(50, 120, 281, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.btn_pedra_2 = QtWidgets.QPushButton(Form)
        self.btn_pedra_2.setGeometry(QtCore.QRect(330, 120, 71, 31))
        self.btn_pedra_2.setStyleSheet("background-color:rgb(127, 127, 127);")
        self.btn_pedra_2.setAutoDefault(True)
        self.btn_pedra_2.setDefault(True)
        self.btn_pedra_2.setObjectName("btn_pedra_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.titulo.setText(_translate("Form", "Jogo Joken Po!"))
        self.btn_pedra.setText(_translate("Form", "Pedra"))
        self.btn_papel.setText(_translate("Form", "Papel"))
        self.btn_tesoura.setText(_translate("Form", "Tesoura"))
        self.btn_reset.setText(_translate("Form", "Resetar"))
        self.btn_pedra_2.setText(_translate("Form", "Enter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
